version: "3.1"

services: 
  database:
    image: "postgres:latest"
    restart: "unless-stopped"
    environment: 
      POSTGRES_DB: "courswsf"
      POSTGRES_USER: "louis"
      POSTGRES_PASSWORD: "azerty"
    volumes:
      - "tp:/var/lib/postgresql/data"
    ports: 
      - "5432:5432"

volumes:
  cours:


version: '2'

services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - "redis-persistence:/bitnami/redis/data"

volumes:
redis-persistence:

# docker-compose up
